version: "3.8"

services:
  db:
    container_name: my_sql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mydatabase"
    ports:
      - 3306:3306
    volumes:
      - django_db:/var/lib/mysql
    ulimits:
      nofile:
        soft: 2000
        hard: 5000

  web:
    container_name: django
    build: .
    ports:
      - 8000:80
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 80:80
    volumes:
      - .:/code/
    depends_on:
      - db

volumes:
  django_db:
